Repository exasol/exasol-virtual-schema, pull requests merged in 2020-11, with the labels that each got.

#29 documentation/Clarify_access_in_case_of_is-local
  doc/dialects/exasol.md
Labels: documentation

#31 * #30: Fixed a CVE-2020-15250 in a transitive dependency.
  doc/changes/changes_3.1.0.md
  pom.xml
Labels: bug

#33 Bug/24 password is exposed in explain virtual for exa connections
  .classpath
  .project
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  .travis.yml
  README.md
  doc/changes/changelog.md
  doc/changes/changes_3.1.0.md
  doc/changes/changes_4.0.0.md
  doc/dialects/exasol.md
  pom.xml
  src/main/java/com/exasol/adapter/dialects/exasol/ExasolConnectionDefinitionBuilder.java
  src/main/java/com/exasol/adapter/dialects/exasol/ExasolProperties.java
  src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialect.java
  src/test/java/com/exasol/adapter/dialects/exasol/AbstractExasolSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/exasol/AbstractExasolSqlDialectIntegrationTest.java
  src/test/java/com/exasol/adapter/dialects/exasol/AbstractRemoteExasolVirtualSchemaConnectionIT.java
  src/test/java/com/exasol/adapter/dialects/exasol/ExasolConnectionDefinitionBuilderTest.java
  src/test/java/com/exasol/adapter/dialects/exasol/ExasolFromExaQueryRewriterTest.java
  src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectAgainstExasolSevenIT.java
  src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectAgainstExasolSixIT.java
  src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectExaConnectionIT.java
  src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectJdbcConnectionIT.java
  src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectLocalConnectionIT.java
  src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectTest.java
  src/test/java/com/exasol/adapter/dialects/exasol/IntegrationTestConfiguration.java
Labels: bug

#35 #34: Use `project-keeper-maven-plugin`
  .settings/org.eclipse.jdt.core.prefs
  .settings/org.eclipse.jdt.ui.prefs
  .travis.yml
  doc/changes/changes_4.0.0.md
  pom.xml
  src/assembly/all-dependencies.xml
  src/main/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialect.java
  src/test/java/com/exasol/adapter/dialects/exasol/AbstractExasolSqlDialectIT.java
  src/test/java/com/exasol/adapter/dialects/exasol/ExasolSqlDialectExaConnectionIT.java
  versionsMavenPluginRules.xml
Labels: refactoring
